service: auth-users-lambda
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs18.x
  environment:
    user_pool_id: "" #adicionar o user pool id
    client_id: "" #adcionar o client id
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminSetUserPassword
      Resource: "*"
functions:
  - ${file(functions.yml)}
custom:
  prune:
    automatic: true
    number: 3

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-dotenv-plugin