name: Terraform AWS Cognito Infrastructure - Create

on:
  workflow_dispatch:

jobs:
  terraform-aws:
    name: "Terraform AWS"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: "Terraform Init"
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: "Terraform Plan"
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve
